#!/bin/bash
# setup_passwordless_ssh.sh
# Run this ONCE to enable passwordless SSH access to Kalpana cluster

echo "==================================================================="
echo "SETUP PASSWORDLESS SSH TO KALPANA CLUSTER"
echo "==================================================================="
echo ""

# Display the public key
echo "Your SSH public key:"
echo ""
cat ~/.ssh/id_rsa.pub
echo ""

echo "==================================================================="
echo "OPTION 1: Automatic Setup (Recommended)"
echo "==================================================================="
echo ""
echo "Run this command and enter password when prompted:"
echo ""
echo "  ssh-copy-id yash.sarang@kalpana.minds.iitb.ac.in"
echo ""
echo "Password: yash.sarang"
echo ""
echo "After this, you'll be able to use 'ssh kalpana' without a password."
echo ""

echo "==================================================================="
echo "OPTION 2: Manual Setup (If ssh-copy-id doesn't work)"
echo "==================================================================="
echo ""
echo "1. SSH to the server:"
echo "   ssh yash.sarang@kalpana.minds.iitb.ac.in"
echo "   (Enter password: yash.sarang)"
echo ""
echo "2. On the server, run:"
echo "   mkdir -p ~/.ssh"
echo "   chmod 700 ~/.ssh"
echo "   nano ~/.ssh/authorized_keys"
echo ""
echo "3. Paste this public key into the file:"
echo ""
cat ~/.ssh/id_rsa.pub
echo ""
echo ""
echo "4. Save and exit (Ctrl+O, Enter, Ctrl+X)"
echo ""
echo "5. Set permissions:"
echo "   chmod 600 ~/.ssh/authorized_keys"
echo ""
echo "6. Exit and test:"
echo "   exit"
echo "   ssh yash.sarang@kalpana.minds.iitb.ac.in"
echo "   (Should work without password)"
echo ""

echo "==================================================================="
echo "OPTION 3: Store Password in SSH Config (Less Secure)"
echo "==================================================================="
echo ""
echo "If you want to store the password (NOT RECOMMENDED for security),"
echo "you can use 'sshpass' or an expect script."
echo ""
echo "Windows users: Install PuTTY and use pageant + plink for"
echo "password-less authentication."
echo ""

echo "==================================================================="
echo "QUICK REFERENCE - SSH Config"
echo "==================================================================="
echo ""
echo "Your SSH config (in ~/.ssh/config) already has:"
echo ""
cat ~/.ssh/config | grep -A 5 "Host kalpana" 2>/dev/null || echo "# No kalpana host found"
echo ""
echo "After passwordless setup, use: ssh kalpana"
echo ""

echo "==================================================================="
echo "NEXT STEPS"
echo "==================================================================="
echo ""
echo "1. Choose OPTION 1 or 2 above"
echo "2. Test connection: ssh yash.sarang@kalpana.minds.iitb.ac.in"
echo "3. If successful, you're done!"
echo ""
echo "==================================================================="
